linux-fml13v01 (6.6.20-3.0ubuntu1) noble; urgency=medium

  * Add more network modules

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Mon, 07 Apr 2025 22:27:45 +0200

linux-fml13v01 (6.6.20-2.0ubuntu1) noble; urgency=medium

  * Enable bridge networking

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Mon, 07 Apr 2025 14:09:17 +0200

linux-fml13v01 (6.6.20-1.1ubuntu4) noble; urgency=medium

  * Enable overlay file-system

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Fri, 04 Apr 2025 13:48:15 +0200

linux-fml13v01 (6.6.20-1.1ubuntu3) noble; urgency=medium

  * Enable kernel compression
  * Create /usr/lib/linux/triggers

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Thu, 20 Mar 2025 11:11:28 +0100

linux-fml13v01 (6.6.20-1.1ubuntu2) noble; urgency=medium

  * Create header files

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Wed, 19 Mar 2025 17:09:00 +0100

linux-fml13v01 (6.6.20-1.1ubuntu1) noble; urgency=medium

  * Create quilt package

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Wed, 12 Mar 2025 19:45:47 +0100

linux-fml13v01 (6.6.20-1.1) noble; urgency=medium

  * Initial packaging

 -- Heinrich Schuchardt <heinrich.schuchardt@canonical.com>  Wed, 12 Mar 2025 14:02:38 +0100
---
arch = "riscv64"
config = "arch/riscv/configs/fml13v01_defconfig"
orig = "v6.6.20"

[pkg.source]
Maintainer = "heinrich.schuchardt@canonical.com"
